name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.135.0'
          extended: true

      - name: Build
        run: hugo --gc --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr
          legacy_allow_rsa_hostkeys: "true"
          path: ./public/
          remote_path: ${{ secrets.HUGO_PATH }}
          remote_port: ${{ secrets.HUGO_PORT }}
          remote_host: ${{ secrets.HUGO_HOST }}
          remote_user: ${{ secrets.HUGO_USER }}
          remote_key_pass: ${{ secrets.HUGO_PASSWORD }}
          remote_key: ${{ secrets.HUGO_KEY }}
